export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  TURF_DETAILS: '/turfs/:turfId',
  SLOT_PICKER: '/turfs/:turfId/slots',
  BOOKINGS: '/bookings',
  REVIEWS: '/reviews',
  TEAMS: '/teams',
  INVITATIONS: '/invitations',
  MATCHES: '/matches',
  TOURNAMENTS: '/tournaments',
  LEADERBOARD: '/leaderboard',
  ADMIN_ANALYTICS: '/admin-analytics',
  OWNER_DASHBOARD: '/owner',
  SETTINGS: '/settings',
};
