server:
  port: 8091

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/analyticsdb}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2.0
  config:
    import: "optional:file:../../config/application-${spring.profiles.active}.yml"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

jwt:
  secret: ${JWT_SECRET:4f7831f13b6329c323f66a877995dc8ab8e92f70b8c6e2646a5b6727282b535d}

logging:
  level:
    com.turfconnect: DEBUG
