server:
  port: 8086

spring:
  application:
    name: review-service
  profiles:
    active: dev
  config:
    import: "optional:file:../../config/application-${spring.profiles.active}.yml"
  data:
    mongodb:
      database: turfconnect_reviews
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
