server:
  port: 8082

spring:
  application:
    name: turf-service
  profiles:
    active: dev
  config:
    import: "optional:file:../../config/application-${spring.profiles.active}.yml"
  data:
    mongodb:
      # Specific database override for Turf service
      uri: ${TURF_MONGO_URI:mongodb://localhost:27017/turfdb}
