server:
  port: 8082

spring:
  application:
    name: turf-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: turfdb

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
